name: Label & comment issues

on:
  issues:
    types:
      - reopened
      - opened
      - closed
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:

  label_issues:
    if: ${{ github.event_name == 'issues' && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach label to issues
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: github.event.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            🙌 Thanks for opening this issue! We'll take a look as soon as possible.

  issue_closed:
    if: ${{ github.event_name == 'issues' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on closed issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: github.event.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ The issue is now resolved.'
            })

  comment_on_first_pr:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: write
    steps:
      - name: Check PR count for the user
        id: pr_check
        uses: actions/github-script@v7
        with:
          script: |
            const result = await github.rest.search.issuesAndPullRequests({
              q: `is:pr author:${context.payload.pull_request.user.login} repo:${context.repo.owner}/${context.repo.repo}`
            });
            core.setOutput("pr_count", result.data.total_count);

      - name: Comment on first pull request
        if: ${{ steps.pr_check.outputs.pr_count == '1' }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: github.event.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: " Congratulations for opening your first pull request!🎉"
            });
